all: date.obj

date.obj: date.cpp
	cl date.cpp
	copy date.exe C:\Users\Yla\Documents\GitHub\SPbCT_IvanovaJA\controlwork\date\bin
	del C:\Users\Yla\Documents\GitHub\SPbCT_IvanovaJA\controlwork\date\bin\date.exe
clean:
	del date.exe
	del date.obj